import { loadEnvFiles } from '../src/lib/env';

loadEnvFiles();

const { db } = await import('../src/core/db');
const { posterSize } = await import('../src/config/db/schema');

const seed = [
  [
    'a4',
    'A4',
    'print',
    'ISO paper',
    210,
    297,
    'mm',
    '1:1.41',
    'The everyday document and flyer format.',
    10,
  ],
  [
    'a3',
    'A3',
    'print',
    'ISO paper',
    297,
    420,
    'mm',
    '1:1.41',
    'A generous sheet for posters, menus, and presentations.',
    20,
  ],
  [
    'a2',
    'A2',
    'print',
    'ISO paper',
    420,
    594,
    'mm',
    '1:1.41',
    'A versatile medium poster size for print shops.',
    30,
  ],
  [
    'a1',
    'A1',
    'print',
    'ISO paper',
    594,
    841,
    'mm',
    '1:1.41',
    'A classic large-format poster for walls and events.',
    40,
  ],
  [
    'a0',
    'A0',
    'print',
    'ISO paper',
    841,
    1189,
    'mm',
    '1:1.41',
    'The largest common ISO sheet for exhibition graphics.',
    50,
  ],
  [
    'a5',
    'A5',
    'print',
    'ISO paper',
    148,
    210,
    'mm',
    '1:1.42',
    'A compact sheet for booklets, menus, and handouts.',
    55,
  ],
  [
    'a6',
    'A6',
    'print',
    'ISO paper',
    105,
    148,
    'mm',
    '1:1.41',
    'A pocket-size format for postcards, flyers, and inserts.',
    56,
  ],
  [
    'b2',
    'B2',
    'print',
    'ISO paper',
    500,
    707,
    'mm',
    '1:1.41',
    'A roomy format for posters, menus, and shop graphics.',
    57,
  ],
  [
    'b1',
    'B1',
    'print',
    'ISO paper',
    707,
    1000,
    'mm',
    '1:1.41',
    'A large exhibition sheet for walls and public displays.',
    58,
  ],
  [
    '16x20',
    '16 × 20 in',
    'print',
    'North America',
    16,
    20,
    'in',
    '4:5',
    'A classic art-print and portrait size for framed work.',
    59,
  ],
  [
    '18x24',
    '18 × 24 in',
    'print',
    'North America',
    18,
    24,
    'in',
    '3:4',
    'A balanced portrait poster used for art prints and events.',
    60,
  ],
  [
    'letter',
    'US Letter',
    'print',
    'North America',
    216,
    279,
    'mm',
    '8.5:11',
    'The everyday North American sheet for documents and flyers.',
    61,
  ],
  [
    'legal',
    'US Legal',
    'print',
    'North America',
    216,
    356,
    'mm',
    '8.5:14',
    'A taller document sheet for contracts and formal notices.',
    62,
  ],
  [
    'tabloid',
    'US Tabloid',
    'print',
    'North America',
    11,
    17,
    'in',
    '11:17',
    'A flexible sheet for spreads, newsletters, and small posters.',
    63,
  ],
  [
    'ledger',
    'US Ledger',
    'print',
    'North America',
    17,
    11,
    'in',
    '17:11',
    'A landscape sheet for plans, tables, and wide layouts.',
    64,
  ],
  [
    '11x14',
    '11 × 14 in',
    'print',
    'North America',
    11,
    14,
    'in',
    '11:14',
    'A compact frame-friendly poster size for art and photography.',
    65,
  ],
  [
    '12x18',
    '12 × 18 in',
    'print',
    'North America',
    12,
    18,
    'in',
    '2:3',
    'A versatile short-run poster size with a tall portrait ratio.',
    66,
  ],
  [
    '20x30',
    '20 × 30 in',
    'print',
    'North America',
    20,
    30,
    'in',
    '2:3',
    'A larger portrait poster for campaigns, events, and walls.',
    67,
  ],
  [
    '22x28',
    '22 × 28 in',
    'print',
    'North America',
    22,
    28,
    'in',
    '11:14',
    'A substantial display print for retail and gallery walls.',
    68,
  ],
  [
    'postcard-4x6',
    'Postcard 4 × 6 in',
    'print',
    'North America',
    4,
    6,
    'in',
    '2:3',
    'A familiar postcard format for direct mail and small promos.',
    69,
  ],
  [
    '24x36',
    '24 × 36 in',
    'print',
    'North America',
    24,
    36,
    'in',
    '2:3',
    'The familiar large portrait poster for campaigns and display.',
    70,
  ],
  [
    'business-card',
    'Business card',
    'print',
    'North America',
    89,
    51,
    'mm',
    '7:4',
    'A standard horizontal card for names, roles, and contact details.',
    71,
  ],
  [
    'rack-card',
    'Rack card',
    'print',
    'North America',
    89,
    216,
    'mm',
    '7:17',
    'A slim handout format made for counters, racks, and takeaways.',
    72,
  ],
  [
    'square-flyer',
    'Square flyer 5 × 5 in',
    'print',
    'North America',
    5,
    5,
    'in',
    '1:1',
    'A compact square for invitations, promos, and art cards.',
    73,
  ],
  [
    '36x48',
    '36 × 48 in',
    'print',
    'North America',
    36,
    48,
    'in',
    '3:4',
    'A large-format poster for storefronts, events, and displays.',
    74,
  ],
  [
    'movie-one-sheet',
    'Movie one-sheet',
    'print',
    'North America',
    27,
    40,
    'in',
    '2:3',
    'The standard theatrical poster format.',
    80,
  ],
  [
    'instagram-square',
    'Instagram post',
    'social',
    'Digital',
    1080,
    1080,
    'px',
    '1:1',
    'A square canvas for feed posts and cover tiles.',
    90,
  ],
  [
    'instagram-story',
    'Instagram story',
    'social',
    'Digital',
    1080,
    1920,
    'px',
    '9:16',
    'A full-screen vertical frame for stories and short video.',
    100,
  ],
  [
    'linkedin-post',
    'LinkedIn post',
    'social',
    'Digital',
    1200,
    627,
    'px',
    '1.91:1',
    'A wide social canvas with room for a headline.',
    110,
  ],
  [
    'presentation-16-9',
    'Presentation 16:9',
    'presentation',
    'Digital',
    1920,
    1080,
    'px',
    '16:9',
    'The default widescreen canvas for decks and display screens.',
    120,
  ],
  [
    'presentation-4-3',
    'Presentation 4:3',
    'presentation',
    'Digital',
    1600,
    1200,
    'px',
    '4:3',
    'The classic presentation ratio for older projectors and slides.',
    130,
  ],
] as const;

await db()
  .insert(posterSize)
  .values(
    seed.map(
      ([
        slug,
        name,
        category,
        region,
        width,
        height,
        unit,
        aspectRatio,
        description,
        sortOrder,
      ]) => ({
        id: `poster-${slug}`,
        slug,
        name,
        category,
        region,
        width,
        height,
        unit,
        aspectRatio,
        description,
        sortOrder,
        status: 'published',
      })
    )
  )
  .onConflictDoNothing();

console.log(`Seeded ${seed.length} Poster Size entries.`);
